### ISSUE TITLE
Use start (alias of Start-Process) as the default

### ISSUE THREAD

**Issue by jonmseaman** [phibr0/obsidian-open-with#5]
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7.2

This is a shell command to open any file with the default program in windows.
That would be a good default to have.

**Comment by phibr0** [comment]
There is already a Command in Obsidian to open a file in the default app. Is this what you are requesting here?

**Comment by jonmseaman** [comment]
Actually, you're totally right. What I'm requesting already exists.
