### ISSUE TITLE
FR: Add `open with` options to the context menu when right-clicking an attachment link 

### ISSUE THREAD

**Issue by chrisgrieser** [phibr0/obsidian-open-with#6]
The core plugin "open with default app" adds the following two items to the context menu, when you right-click an attachment link
<img width="612" alt="Screenshot 2022-01-07 22 00 37" src="https://user-images.githubusercontent.com/73286100/148607154-4d8934cc-76a9-42f5-974b-256785c02518.png">

It could be quite useful to add such context menu items to this plugin as well, e.g. to open images in an image app.

**Comment by phibr0** [comment]
![image](https://user-images.githubusercontent.com/59741989/148640165-e06ab8f3-9624-4490-b3c1-74fcc967fc81.png)

In version 0.3.0 you can configure whether you want the app in the File menu or not.

**Comment by chrisgrieser** [comment]
fantastic. And having toggles to enable which ones to show is a great bonus. Thanks! 😊

**Comment by chrisgrieser** [comment]
Minor follow up: Could you also add the `show file in system explorer` command to the context menu as well? 🙏

**Comment by phibr0** [comment]
![image](https://user-images.githubusercontent.com/59741989/149185593-689ec71e-c0e2-4f9c-a3ee-805272a91dd7.png)

Isn't that already included by default?

**Comment by chrisgrieser** [comment]
yes, but it's dependent on the "Open with Default app" plugin being enabled. However, your plugin is basically a replacement/improvement of that plugin, and to fully replace it, that's I think the only thing missing ;)

(It's not really a big issue for, just regarding completeness, and I assume it's easily implemented)

**Comment by phibr0** [comment]
Okay! Added in the new release.

**Comment by chrisgrieser** [comment]
thank you 💙
